server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
       name: RESTAURANT-SERVICE
  datasource:
         url: jdbc:mysql://localhost:3306/restaurant
         driver-class-name: com.mysql.cj.jdbc.Driver
         password: Aziz12345@
         username: root

  jpa:
       hibernate.ddl-auto: update
       generate-ddl: true
       show-sql: true
       database-platform: org.hibernate.dialect.MySQL8Dialect
